version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: optimix-preferans
      runtime: image
      image:
        url: ivanmilenkovic/pref:1.6.30
        creds:
          fromRegistryCreds:
            name: Docker read
      plan: free
      envVars:
        - key: ASPNETCORE_ENVIRONMENT
          value: production
      region: frankfurt
      autoDeployTrigger: commit
    - type: keyvalue
      name: redis
      plan: free
      region: frankfurt
      maxmemoryPolicy: allkeys-lru
      ipAllowList: []

